[env:seeed_xiao_nrf52840_sense]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840
framework = arduino

board_build.core = nRF5          ; force le core Adafruit (Bluefruit)

monitor_speed = 115200

build_flags =
    -DTARGET_SEEED_XIAO_NRF52840_SENSE
    -DHAS_INCLUDE_FS_H

lib_deps =
    seeed-studio/Seeed Arduino LSM6DS3@^2.0.5
    sparkfun/SparkFun u-blox GNSS Arduino Library@^2.2.27
    adafruit/Adafruit SPIFlash
    adafruit/Adafruit TinyUSB Library
